const List<String> tags = [
  '2-sat',
  'meet-in-the-middle',
  'binary search',
  'bitmasks',
  'fft',
  'geometry',
  'graphs',
  'two pointers',
  'trees',
  'dp',
  'greedy',
  'games',
  'interactive',
  'chinese remainder theorem',
  'combinatorics',
  'constructive algorithms',
  'shortest paths',
  'math',
  'matrices',
  'graph matchings',
  'brute force',
  'dfs and similar',
  'flows',
  'expression parsing',
  'divide and conquer',
  'schedules',
  'implementation',
  'dsu',
  'sortings',
  'strings',
  'string suffix structures',
  'data structures',
  'probabilities',
  'number theory',
  'ternary search',
  'hashing',
];
